### ISSUE TITLE
Error when using `allowed`

### ISSUE THREAD

**Issue by todor-a** [es-tooling/eslint-plugin-depend#26]
I've copy-pasted the example from the docs for the `allowed` option, but get the following error:
```
Oops! Something went wrong! :(

ESLint: 8.57.0

Error: .eslintrc:
        Configuration for rule "depend/ban-dependencies" is invalid:
        Value {"allowed":["is-nan"]} should NOT have additional properties.

    at ConfigValidator.validateRuleOptions (myapp/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2048:23)
    at myapp/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2103:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (myapp/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2100:34)
    at ConfigValidator.validateConfigArray (myapp/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2226:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (myapp/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3985:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (myapp/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3791:21)
    at FileEnumerator._iterateFilesRecursive (myapp/node_modules/eslint/lib/cli-engine/file-enumerator.js:450:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (myapp/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:49)
```

`.eslintrc`:
```
{
  "extends": [
        "plugin:depend/recommended"
    ],
   "rules": {
        "depend/ban-dependencies": ["error", {
            "allowed": ["is-nan"]
          }],
    }
}
```

**Comment by 43081j** [comment]
The version with this option in hasn't yet been released. I've been out travelling so struggling to find time to push one

I'll do what I can and get one released this week

**Comment by todor-a** [comment]
@43081j I've missed that. No worries, thank you.

**Comment by 43081j** [comment]
should be released and working now 👍
